image:
- Visual Studio 2017
- Ubuntu

stack: node 8
environment:
  nodejs_version: "8"
  VSTS_ARTIFACTORY_URL:
    secure: RIh0gGFDn2JAnLUEEqLsQnZ5H3XFWg1s+Qq8Z4i+Xu+FtQf6Tsu2AnfY4/6AaXJ8
  VSTS_ARTIFACTORY_USERNAME:
    secure: YEB5Wiv9a2vNpUhy+MfL+A==
  VSTS_ARTIFACTORY_PASSWORD:
    secure: Um8o75MQIieSavIemF4ySA==

install:
  - npm install -g jfrog-cli-go

test_script:
  - node --version
  - npm --version
  - npm test

# Don't actually build.
build: off
