image:
- Visual Studio 2017
- Ubuntu

stack: node 8
environment:
  nodejs_version: "8"
  VSTS_ARTIFACTORY_URL:
    secure: KkjTm9RrjPrzDQocmxTmQPdE2bozPgix5CFjkeam6Fscx1S34tR4Hpqg3j/7R+AH
  VSTS_ARTIFACTORY_USERNAME:
    secure: b79qvuMVVlqhdsKoJC046g==
  VSTS_ARTIFACTORY_PASSWORD:
    secure: eebX+bKmzB9hHtjniAvmXQYLqNSWPxPwy71sOeNLrkU=

install:
  - npm install -g jfrog-cli-go

test_script:
  - node --version
  - npm --version
  - sh: if [[ "$APPVEYOR_REPO_BRANCH" = "dev" && -z "$APPVEYOR_PULL_REQUEST_TITLE" ]]; then
          npm test;
        fi
  - cmd: IF "%APPVEYOR_REPO_BRANCH%" == "dev IF "%APPVEYOR_PULL_REQUEST_TITLE%" == "" (
           npm test
         )

# Don't actually build.
build: off
