build: off
stack: node 10, python 3.9, jdk 8
skip_tags: true
environment:
  matrix:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        ADO_ARTIFACTORY_SKIP_TESTS: docker
      - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

  nodejs_version: "10"
  ADO_ARTIFACTORY_URL:
    secure: RIh0gGFDn2JAnLUEEqLsQnZ5H3XFWg1s+Qq8Z4i+Xu+FtQf6Tsu2AnfY4/6AaXJ8
  ADO_ARTIFACTORY_USERNAME:
    secure: YEB5Wiv9a2vNpUhy+MfL+A==
  ADO_ARTIFACTORY_PASSWORD:
    secure: Um8o75MQIieSavIemF4ySA==
  ADO_ARTIFACTORY_DOCKER_DOMAIN:
    secure: ppjr6mrLIKXVptLX8WPOlffTwOLtRIoaIpsVEvmje/9mDtLojTqpwI9OIC5VZnx1
  ADO_ARTIFACTORY_DOCKER_REPO:
    secure: UjixvF6E1Bp1p8zgPRLCVA==

install:
- cmd: powershell Install-Product node $env:nodejs_version
- npm i -gq jfrog-cli-go
- sh: sudo pip install conan -q
- cmd: pip install conan -q
- cmd: nuget update -self
- cmd: set PATH=C:\Python37;C:\Python37\Scripts;%PATH%

services:
- docker

test_script:
- node --version
- npm --version
- npm t
- npm run create # Make sure that that the extension can be created
