image:
- Visual Studio 2017
- Ubuntu

build: off
stack: node 8
skip_tags: true
environment:
  nodejs_version: "8"
  VSTS_ARTIFACTORY_URL:
    secure: RIh0gGFDn2JAnLUEEqLsQnZ5H3XFWg1s+Qq8Z4i+Xu+FtQf6Tsu2AnfY4/6AaXJ8
  VSTS_ARTIFACTORY_USERNAME:
    secure: YEB5Wiv9a2vNpUhy+MfL+A==
  VSTS_ARTIFACTORY_PASSWORD:
    secure: Um8o75MQIieSavIemF4ySA==

install:
- npm install -g jfrog-cli-go
- npm install -g tfx-cli

test_script:
- node --version
- npm --version
- npm run create # Make sure that that the extension can be created
- npm t
